name: call_transcript
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.5
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  flutter_audio_waveforms: ^1.2.1+8
  flutter_svg: ^2.0.10+1
  just_waveform: ^0.0.5
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
